dist: trusty

language: php
php:
    - nightly
    - 7.4
    - 7.3
    - 7.2
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4

env:
    - LIBZMQ_VERSION=2.2.0
    - LIBZMQ_VERSION=3.2.5
    - LIBZMQ_VERSION=4.0.7 LIBSODIUM_VERSION=1.0.8
    - LIBZMQ_VERSION=4.1.4 LIBSODIUM_VERSION=1.0.8
    - LIBZMQ_VERSION=master LIBSODIUM_VERSION=1.0.18
addons:
    apt:
        packages:
            - uuid-dev
            - libtool

before_script:
  - phpenv config-rm xdebug.ini || true

script: travis/script.sh $HOME/zeromq-cache $LIBZMQ_VERSION $LIBSODIUM_VERSION $CZMQ_VERSION

sudo: false

cache:
  directories:
  - $HOME/zeromq-cache
